# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pDlt+Uemtbd98NKgly5f0WQlBz0LByxhKpWtOMOQLXk=,iv:aCsDET0yXgOoTJF+tCIfeTuzk6QVuKvWjKC7cMA0yug=,tag:KqP4GR/HLo6hLdssCuyouA==,type:str]
sops:
  age:
    - recipient: age1a3n0nnyg97hethp49t7a07xk2dty4j2g4pqr6gvzhx3esrvx3f4qqmk0tc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzT0lDSHBjQTN1emhWYXJW
        RGl3YUxmVzlTVjlxQVh6YWJkYzNicWxmR2pRCllLYWhmdVpydVdUeWtWN3FkRFpV
        azdxcTU0SXpSeUhtNHk1STBzL0QwNXcKLS0tIG1MOFhWd0NGYk83RzdDY0tzQWRC
        Nkp4WWc5N2VaOEVEV0pCZGxNeFMvd3cKlBiCoN6sFK7B96HU+u8Y6RDKwSmIT8iD
        DvVCW6imG1qBROFdYiuNFidMjZa6a7ubYbp4LqU9tTktGkpj9u9EKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-21T09:18:54Z"
  mac: ENC[AES256_GCM,data:7pEsM0zgr3olijXxLWzPGN3BcSlVvOOix2oscunaX/i+8B7vwO98QZ9kBq5CF1ciMibrT7gRnr7Fq5+0NyjHMxeDLRionKUezHZzkUwWPd+RTwrOyr777A7xFzTLOLr6GU1+vd+1VFM6OneL79HSC3z+w8fGkKlpuDupe6jlPrg=,iv:INGn1ozKGEFPdnBniRymZ9Wgo77awj0ZfzGJpkM4ArM=,tag:kxiwUFjcZz17YKbZ2TDzWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
